#!/bin/sh
# chronyd — NTP-клиент/сервер (точное время)
#  Arch/systemd:  systemctl enable --now chronyd.service
#  Void:          chrony пакет, юзер chrony уже создан пакетом
case $1 in
start)
	install -d -m750 -o chrony -g chrony /var/run/chrony
	exec chronyd -n -u chrony
	;;
stop) pkill chronyd ;;
esac