#!/bin/sh
# hostname — имя хоста из /etc/hostname + ping_group_range (для не-root ping)
#  Arch/systemd:  systemd-hostnamed.service; /etc/hostname читает systemd сам
#  Void:          этот скрипт
case $1 in
start)
	cat /etc/hostname > /proc/sys/kernel/hostname
	echo '0 2147483647' > /proc/sys/net/ipv4/ping_group_range
	;;
stop) ;;
esac