#!/bin/sh
case $1 in
start)
	/usr/bin/ip link set lo up
	for i in /sys/class/net/*; do
		[ "${i##*/}" = lo ] || /usr/bin/ip link set "${i##*/}" up
	done
	exec /usr/local/sbin/sdhcp -d enp3s0
	;;
stop) pkill sdhcp ;;
esac
