#!/bin/sh
case $1 in
start)
	/usr/bin/udevd &
	( sleep 1; udevadm trigger --action=add --type=subsystems; udevadm trigger --action=add --type=devices; udevadm settle --timeout=30 ) &
	wait
	;;
stop) pkill udevd ;;
esac
